baseURL = "http://example.org/"
languageCode = "de-de"
title = "Antik Ameln"
assetDir = "/static/"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
[[menu.mainmenu]]
name = "references"
title = "Referenzen"
weight = 8

[[module.mounts]]
source = "static"
target = "assets"
